GET https://api.chucknorris.io/jokes/random HTTP/1.1

###

GET https://api.chucknorris.io/jokes/random?category=celebrity HTTP/1.1

###

GET https://www.genesis10.com/dev10 HTTP/1.1

###

GET https://assets.chucknorris.host/img/avatar/chuck-norris.png HTTP/1.1

###

GET http://localhost:8080/name HTTP/1.1

### Name

GET /name HTTP/1.1
Host: localhost:8080

### What time is it?

GET http://localhost:8080/current/time HTTP/1.1

### Greeting

GET http://localhost:8080/greet/dave HTTP/1.1

### Counting sheep

PUT http://localhost:8080/sheep HTTP/1.1

### How many sheep?

GET http://localhost:8080/sheep HTTP/1.1

### Increase sheep by amount

PUT http://localhost:8080/sheep/5 HTTP/1.1

### Increase sheep by object (needs to be called amount because that is the name of the field in the model)

POST http://localhost:8080/sheep HTTP/1.1
Content-Type: application/json

{
    "amount":"3" 
}

### Lost sheep

DELETE http://localhost:8080/sheep HTTP/1.1

### Todos

GET http://localhost:8080/todo HTTP/1.1

### Add list to todos

PUT http://localhost:8080/todo HTTP/1.1
Content-Type: application/json

["Shop","Fly","Run"]

### Add one item to todos

PUT http://localhost:8080/todo/feed%20cat HTTP/1.1

### Delete one item

DELETE http://localhost:8080/todo/2 HTTP/1.1

### Replace list with given one

POST http://localhost:8080/todo HTTP/1.1
Content-Type: application/json

[
    "New item 1",
    "New item 2"
]