package learn.solarpanels.models;

public enum MaterialType {
    MONOCRYSTALLINE_SILICON,
    MULTICRYSTALLINE_SILICON,
    AMORPHOUS_SILICON,
    CADMIUM_TELLURIDE,
    COPPER_INDIUM_GALLIUM_SELENIDE
}
