@url = http://localhost:8080/api/video-game

GET {{url}} HTTP/1.1

### Should find game
GET {{url}}/3 HTTP/1.1

### Shouldnt find game
GET {{url}}/99 HTTP/1.1

###
POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "title": "Stray",
    "console": "PC",
    "price": 20.00,
    "releaseDate": "2022-06-11",
    "singlePlayer": true
}

### Should fail to add a game, 400

POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "title": "Stray",
    "console": "PC!!",
    "price": 75.00,
    "releaseDate": "2022-06-11",
    "singlePlayer": true
}


### Should update a game 204

PUT {{url}}/4 HTTP/1.1
Content-Type: application/json

{
    "id":4,
    "title": "Did I update?",
    "console": "SWITCH",
    "price": 1.00,
    "releaseDate": "2022-01-01",
    "singlePlayer": false
}

### Should delete game

DELETE {{url}}/4 HTTP/1.1

### Should not delete game 400

DELETE {{url}}/99 HTTP/1.1